# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_server(object):
    def setupUi(self, server):
        server.setObjectName("server")
        server.resize(400, 300)
        server.setMinimumSize(QtCore.QSize(400, 300))
        server.setMaximumSize(QtCore.QSize(400, 300))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        server.setFont(font)
        self.hint = QtWidgets.QTextBrowser(server)
        self.hint.setGeometry(QtCore.QRect(10, 10, 381, 201))
        self.hint.setObjectName("hint")
        self.start = QtWidgets.QPushButton(server)
        self.start.setGeometry(QtCore.QRect(300, 220, 91, 31))
        self.start.setObjectName("start")
        self.terminate = QtWidgets.QPushButton(server)
        self.terminate.setGeometry(QtCore.QRect(300, 260, 91, 31))
        self.terminate.setObjectName("terminate")
        self.IPAddress = QtWidgets.QLineEdit(server)
        self.IPAddress.setGeometry(QtCore.QRect(10, 220, 281, 31))
        self.IPAddress.setObjectName("IPAddress")
        self.port = QtWidgets.QLineEdit(server)
        self.port.setGeometry(QtCore.QRect(10, 260, 281, 31))
        self.port.setObjectName("port")

        self.retranslateUi(server)
        QtCore.QMetaObject.connectSlotsByName(server)

    def retranslateUi(self, server):
        _translate = QtCore.QCoreApplication.translate
        server.setWindowTitle(_translate("server", "SafeChatroom-Server"))
        self.hint.setHtml(_translate("server", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">Set IP address and port for the server. Clients will access this server through these information.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">The form of IP address should look like:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">127.0.0.1</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">The form of port number should look like:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">8000</span></p></body></html>"))
        self.start.setText(_translate("server", "Start"))
        self.terminate.setText(_translate("server", "Terminate"))
